version: '3'
services:
  100knock:
    container_name: nlp100knock
    image: nlpbook:onmyway
    volumes:
      - './:/nlp100knock'
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    tty: true